modLoader = "javafml"
loaderVersion = "[50,)"
issueTrackerURL = "${mod_issues_url}"
license = "${copyright_licence}"

[[mods]]
modId = "civmodern"
version = "${mod_version}"
displayName = "CivModern"
description = "${mod_description}"
displayURL = "${mod_home_url}"
authors = "Okx"
#logoFile = ""

[[dependencies.civmodern]]
modId = "forge"
mandatory = true
versionRange = "[50,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.civmodern]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "CLIENT"
