modLoader = "javafml"
loaderVersion = "[${forge_loader_major_version},)"
issueTrackerURL = "${mod_issues_url}"
license = "${copyright_licence}"

[[mods]]
modId = "civmodern"
version = "${mod_version}"
displayName = "${mod_name}"
description = "${mod_description}"
displayURL = "${mod_home_url}"
authors = "${mod_authors}"
#logoFile = ""

[[dependencies.civmodern]]
modId = "forge"
mandatory = true
versionRange = "[${forge_loader_major_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.civmodern]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "CLIENT"
